
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationPlaceHold","number":89,"title":"Added UCSBOrganization PlaceHolders","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/89"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationTableCom","number":87,"title":"Added UCSBOrganization Table & Tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/87"},{"author":{"id":"U_kgDOBXdYPQ","is_bot":false,"login":"aditiphatak","name":"Aditi Phatak"},"headRefName":"Aditi-RecommendationRequest-backend","number":85,"title":"Recommendation Request Backend (Adding Form Component and Tests) ","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/85"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-placeholder","number":84,"title":"Copy Placeholders for MenuItemReview pages; add to App.js/AppNavbar.js","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/84"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-table","number":83,"title":"Table Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/83"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationIndexPage","number":81,"title":"Added UCSBOrganization Index Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/81"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationCreatePage","number":80,"title":"Added UCSBOrganization Create Page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/80"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-form","number":79,"title":"Form Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/79"}]
