
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-form","number":79,"title":"Form Component for MenuItemReview plus tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/79"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-MenuItemEditPage","number":78,"title":"Edit Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/78"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-MenuItemIndexPage","number":77,"title":"Index Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/77"},{"author":{"id":"MDQ6VXNlcjY0Mjg2NjM1","is_bot":false,"login":"katytsao","name":"Katy Tsao"},"headRefName":"Katy-Articles-backend","number":76,"title":"Copy files for Backend CRUD API Articles","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/76"},{"author":{"id":"MDQ6VXNlcjU5MjUwODA=","is_bot":false,"login":"ajs808","name":"Arul Saxena"},"headRefName":"Arul-MenuItemCreatePage","number":75,"title":"Create Page for UCSBDiningCommonsMenuItem plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/75"},{"author":{"id":"MDQ6VXNlcjU0Mjg0MTQ4","is_bot":false,"login":"kendrick-lee","name":""},"headRefName":"Kendrick-UCSBOrganizationForm","number":72,"title":"Added UCSBOrganization Form & Tests","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/72"}]
