
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team03-f23-5pm-4
owner: ucsb-cs156-f23
repo_name: team03-f23-5pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjY0Mjg2NjM1","is_bot":false,"login":"katytsao","name":"Katy Tsao"},"headRefName":"Aditi-RecommendationRequest-EditPage","number":111,"title":"Aditi recommendation request edit page","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/111"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequest-Frontend-indexpart2","number":110,"title":"Index Page for HelpRequest plus tests and stories #50","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/110"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequest-Frontend-CreatePage","number":109,"title":"Create Page for HelpRequest plus tests and stories #49","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/109"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequest-Frontend-placeholders","number":105,"title":"Copy Placeholders for HelpRequest pages; add to App.js/AppNavbar.js #48","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/105"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-edit","number":104,"title":"Edit Page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/104"},{"author":{"id":"MDQ6VXNlcjI1NTMzNjIw","is_bot":false,"login":"Francisc0Leyva","name":"Francisco Justin Leyva"},"headRefName":"Justin-HelpRequest-Frontend-Tables","number":103,"title":"Table Component for HelpRequest plus tests #47","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/103"},{"author":{"id":"MDQ6VXNlcjQ2Njk2NDkw","is_bot":false,"login":"mitali-g","name":"Mitali Gaidhani"},"headRefName":"Mitali-MenuItemReview-create","number":94,"title":"Create Page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-f23/team03-f23-5pm-4/pull/94"}]
